version: '3.8'

services:

  postgres-dev: 
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: gnark
      POSTGRES_DB: oasis
    ports:
      - 5432:5432
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
