version: '3.8'

services:

  postgres-dev: 
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: gnark
      POSTGRES_DB: oasis
    ports:
      - 5432:5432

  postgres-test: 
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: gnark
      POSTGRES_DB: oasis
    ports:
      - 5433:5433

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379
    
